print("Welcome to the tip calculator!")
total_bill = float(input("What was the total bill? $"))
tip = float(input("How much tip would you like to give? 10, 12 or 15? "))
people_to_split = int(input("How many people to split the bill? "))
each_pay = float((total_bill + tip * total_bill / 100) / people_to_split)
print(f"Each person should pay: {round(each_pay,2)}")
